"""MANIFEST_CANONICAL.json verification (Rule R2 / battle plan D4).

For each anchor marked `policy: immutable`, re-hash the file's bytes
on disk and compare to the pinned `sha256`. A mismatch is the most
serious failure mode the system has — it triggers LOCKDOWN, which
refuses all forward operations until an operator clears it.

Note on Windows checkouts: anchored files should also be locked in
`.gitattributes` with `-text` so the working-tree bytes equal the git
blob bytes (i.e. so this routine matches what CI verifies). If
working-tree CRLF normalization slips in, this routine surfaces it as
drift — which is correct behavior; the operator must refresh the
working tree.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import NoReturn


class LockdownError(RuntimeError):
    """Raised when canonical anchor verification fails or other
    LOCKDOWN-class conditions are detected. Forward operations halt
    until the operator clears `BLOCKED.md`."""


@dataclass(frozen=True, slots=True)
class CanonicalCheck:
    """Result of verifying one anchor."""

    anchor_id: str
    path: str
    policy: str
    expected_sha256: str | None
    got_sha256: str | None
    ok: bool
    error: str | None = None  # populated on file-missing / IO error

    @property
    def descriptor(self) -> str:
        if self.ok:
            return f"OK  {self.path}  sha256={self.expected_sha256[:16] if self.expected_sha256 else '?'}…"
        if self.error:
            return f"ERR {self.path}  {self.error}"
        return (
            f"DRIFT {self.path}\n"
            f"  expected: {self.expected_sha256}\n"
            f"  got:      {self.got_sha256}"
        )


def load_manifest_canonical(repo_path: str | Path) -> dict:
    """Read and parse MANIFEST_CANONICAL.json. Raises on missing/invalid."""
    p = Path(repo_path) / "MANIFEST_CANONICAL.json"
    if not p.is_file():
        raise FileNotFoundError(
            f"MANIFEST_CANONICAL.json not found at {p}"
        )
    return json.loads(p.read_text(encoding="utf-8"))


def verify_canonical(repo_path: str | Path) -> list[CanonicalCheck]:
    """Re-hash every immutable anchor; return per-anchor results.

    A repo with no anchors (e.g. Platform pre-Phase J) yields an empty
    list, which the caller should treat as "vacuously ok".
    """
    repo = Path(repo_path)
    manifest = load_manifest_canonical(repo)
    results: list[CanonicalCheck] = []
    for anchor in manifest.get("anchors", []):
        policy = anchor.get("policy", "")
        if policy != "immutable":
            continue
        rel = anchor["path"]
        anchor_id = anchor.get("id", rel)
        expected = anchor.get("sha256")
        target = repo / rel
        try:
            data = target.read_bytes()
        except OSError as e:
            results.append(
                CanonicalCheck(
                    anchor_id=anchor_id,
                    path=rel,
                    policy=policy,
                    expected_sha256=expected,
                    got_sha256=None,
                    ok=False,
                    error=f"read failed: {e!s}",
                )
            )
            continue
        got = hashlib.sha256(data).hexdigest()
        results.append(
            CanonicalCheck(
                anchor_id=anchor_id,
                path=rel,
                policy=policy,
                expected_sha256=expected,
                got_sha256=got,
                ok=(got == expected),
            )
        )
    return results


def enter_lockdown(reason: str, blocked_path: Path) -> NoReturn:
    """Write a minimal BLOCKED.md and raise LockdownError.

    The full five-section halt report is the operator's domain; this
    function writes a machine-generated stub that the operator
    enriches by hand. We don't sys.exit() — the caller decides how to
    propagate the halt.
    """
    blocked_path.parent.mkdir(parents=True, exist_ok=True)
    blocked_path.write_text(
        "# Blocked\n\n"
        "**Generated by:** symverify.canonical.enter_lockdown\n\n"
        "## 1. What just happened\n\n"
        f"{reason}\n\n"
        "## 2. Why halted\n\n"
        "Rule R2 / Rule R1: canonical anchor verification failed; the\n"
        "system is in LOCKDOWN. Forward operations refuse until an\n"
        "operator confirms the cause and resolves the bracket.\n\n"
        "## 3. What is needed\n\n"
        "Operator investigation required. See `BRACKETS.json` for the\n"
        "non-zero charge(s) and `LOG.md` for the most recent audit.\n\n"
        "## 4. Where work resumes\n\n"
        "After the operator confirms anchors are restored or explicitly\n"
        "rotates Q_canonical's expected_value (an evolution event\n"
        "requiring its own commit per `_command/07_EQUATION_INTEGRATION.md`\n"
        "§6).\n\n"
        "## 5. Affected `{Q_A, H_S}`\n\n"
        "At minimum `Q_canonical` is non-zero. Full per-charge values:\n"
        "see `BRACKETS.json`.\n",
        encoding="utf-8",
    )
    raise LockdownError(reason)
