"""`sym scaffold <repo>/<app-name>` — generate a Symmetism-tracked app skeleton.

Battle-plan F11.2 says: an operator should get a runnable, manifest-
exposing FastAPI app + Dockerfile + Caddy block in one command. The
GHA build-and-publish workflow already detects new `apps/<name>/`
dirs that contain a Dockerfile, so the only manual step after
scaffolding is editing the app's logic and pushing.

What this writes (under <repo>/apps/<app-name>/):

  pyproject.toml          minimal hatchling FastAPI project
  Dockerfile              two-stage python:3.12-slim, healthcheck on /healthz
  README.md               1-paragraph stub
  src/<pkg>/__init__.py   __version__ = "0.1.0"
  src/<pkg>/main.py       FastAPI app; /healthz; attach_manifest_endpoint
  src/<pkg>/manifest_endpoint.py
                          self-contained /__manifest helper (FastAPI flavor)
  caddy-snippet.txt       reverse_proxy block for the operator to merge
                          into server/Caddyfile by hand

Idempotent: if the target dir already exists, scaffold refuses to clobber
unless `force=True`. We never write to other repos' state — only the
repo path resolved from <repo>.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from symverify import config


class ScaffoldError(RuntimeError):
    """Raised when scaffolding cannot proceed (e.g. dir exists)."""


_NAME_RE = re.compile(r"^[a-z][a-z0-9-]{1,40}$")


def _validate_app_name(name: str) -> None:
    if not _NAME_RE.match(name):
        raise ScaffoldError(
            f"app name {name!r} must match {_NAME_RE.pattern} "
            "(lowercase, dashes ok, 2-41 chars, starts with letter)"
        )


def _pkg_name(app_name: str) -> str:
    """Convert dash-name to snake-name for the Python package."""
    return app_name.replace("-", "_")


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------


def _pyproject(app_name: str, pkg_name: str) -> str:
    return f"""\
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{app_name}"
version = "0.1.0"
description = "Symmetism-tracked app: {app_name}"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
authors = [
  {{ name = "Symmetism", email = "Symmetist@users.noreply.github.com" }},
]
dependencies = [
  "fastapi>=0.110",
  "uvicorn[standard]>=0.27",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/{pkg_name}"]
"""


def _dockerfile(app_name: str, pkg_name: str, repo: str) -> str:
    return f"""\
# syntax=docker/dockerfile:1.7
#
# {app_name} container — generated by `sym scaffold`.
# Build context = REPO ROOT so `apps/{app_name}/` paths resolve.

FROM python:3.12-slim-bookworm AS builder

ENV PIP_NO_CACHE_DIR=1 \\
    PIP_DISABLE_PIP_VERSION_CHECK=1 \\
    PYTHONDONTWRITEBYTECODE=1

WORKDIR /build
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY apps/{app_name}/pyproject.toml /build/pyproject.toml
RUN pip install --no-cache-dir \\
    "fastapi>=0.110" \\
    "uvicorn[standard]>=0.27"

FROM python:3.12-slim-bookworm AS runtime

ARG IMAGE_GIT_SHA="unknown"

LABEL org.opencontainers.image.title="{app_name}" \\
      org.opencontainers.image.description="Symmetism-tracked app: {app_name}" \\
      org.opencontainers.image.source="https://github.com/Symmetism/{repo.capitalize()}" \\
      org.opencontainers.image.licenses="MIT" \\
      org.opencontainers.image.revision="${{IMAGE_GIT_SHA}}"

RUN groupadd --system --gid 10001 app \\
 && useradd  --system --uid 10001 --gid app --home /home/app --shell /sbin/nologin app

RUN apt-get update \\
 && apt-get install -y --no-install-recommends curl ca-certificates \\
 && rm -rf /var/lib/apt/lists/*

COPY --from=builder /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH" \\
    PYTHONUNBUFFERED=1 \\
    PYTHONDONTWRITEBYTECODE=1 \\
    IMAGE_GIT_SHA="${{IMAGE_GIT_SHA}}"

WORKDIR /app
COPY --chown=app:app apps/{app_name}/src/ /app/src/

USER app
EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
    CMD curl --fail --silent http://127.0.0.1:8000/healthz || exit 1

CMD ["uvicorn", "{pkg_name}.main:app", \\
     "--host", "0.0.0.0", "--port", "8000", \\
     "--app-dir", "/app/src", \\
     "--proxy-headers", \\
     "--forwarded-allow-ips", "*"]
"""


def _readme(app_name: str) -> str:
    return f"""\
# {app_name}

Symmetism-tracked app generated by `sym scaffold`. Exposes a FastAPI
service on port 8000 with `/healthz` and an authenticated
`/__manifest` endpoint for SymVerify's third trinity leg.

## Local

    cd apps/{app_name}
    pip install -e .
    uvicorn {_pkg_name(app_name)}.main:app --reload

## Deploy

The build-and-publish GHA workflow detects this directory at next
push; the resulting image lands at
`ghcr.io/symmetism/{app_name}:<sha>`. Add the snippet from
`caddy-snippet.txt` to `server/Caddyfile`, register the app in
`server/compose.yaml`, and Watchtower rolls it within ~60 s.
"""


def _init_py(app_name: str) -> str:
    return f'"""Symmetism app: {app_name}."""\n\n__version__ = "0.1.0"\n'


def _main_py(app_name: str, pkg_name: str) -> str:
    return f'''\
"""Entry point for {app_name} — FastAPI app skeleton.

Mounts /healthz and /__manifest (the latter via attach_manifest_endpoint).
Add your own routes below the marker. Don't remove /__manifest — SymVerify
relies on it for the server leg of the trinity.
"""

from __future__ import annotations

from fastapi import FastAPI

from {pkg_name} import __version__
from {pkg_name}.manifest_endpoint import attach_manifest_endpoint

app = FastAPI(
    title="{app_name}",
    version=__version__,
    docs_url=None, redoc_url=None, openapi_url=None,
)

attach_manifest_endpoint(app)


@app.get("/healthz")
def healthz():
    return {{"ok": True, "version": __version__}}


# --- your routes below -----------------------------------------------------


@app.get("/")
def root():
    return {{"app": "{app_name}", "version": __version__}}
'''


def _manifest_endpoint_py(pkg_name: str) -> str:
    return '''\
"""FastAPI flavor of the /__manifest helper.

Mirrors the Flask version in Reflexivity but uses FastAPI's request
plumbing. SHA-256s the deployed bytes once at startup; serves the
cached body on every authenticated request.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import os
import unicodedata
from datetime import datetime, timezone
from pathlib import Path

from fastapi import FastAPI, Header, HTTPException, Response

SPEC_VERSION = "symverify-fingerprint/1"
_SKIP_PARTS = {"__pycache__", ".pytest_cache", ".cache"}
_SKIP_PREFIXES = (".git",)


def _normalize_path(p: str) -> str:
    return unicodedata.normalize("NFC", p.replace("\\\\", "/"))


def _normalize_mode(mode: int) -> int:
    return 0o100755 if mode & 0o111 else 0o100644


def _walk_files(root: Path):
    for p in root.rglob("*"):
        if not p.is_file():
            continue
        rel_parts = p.relative_to(root).parts
        if any(part in _SKIP_PARTS for part in rel_parts):
            continue
        if any(part.startswith(_SKIP_PREFIXES) for part in rel_parts):
            continue
        yield p


def compute_app_manifest(repo_root: str | Path = "/app") -> dict:
    root = Path(repo_root)
    entries: list[dict] = []
    for p in _walk_files(root):
        rel = _normalize_path(str(p.relative_to(root)))
        st = p.stat()
        data = p.read_bytes()
        entries.append({
            "path": rel,
            "mode": _normalize_mode(st.st_mode),
            "size": len(data),
            "sha256": hashlib.sha256(data).hexdigest(),
        })
    entries.sort(key=lambda e: e["path"].encode("utf-8"))
    canonical = json.dumps(entries, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    return {
        "spec": SPEC_VERSION,
        "manifest_root_hash": hashlib.sha256(canonical).hexdigest(),
        "file_count": len(entries),
        "commit_sha": os.environ.get("IMAGE_GIT_SHA", "unknown"),
        "built_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "version": os.environ.get("FRAMEWORK_VERSION", "unknown"),
    }


def attach_manifest_endpoint(
    app: FastAPI,
    *,
    repo_root: str | Path = "/app",
    token_env: str = "SYMVERIFY_TOKEN",
    route: str = "/__manifest",
):
    cached = compute_app_manifest(repo_root)
    cached_body = json.dumps(cached, ensure_ascii=False).encode("utf-8")
    expected_token = os.environ.get(token_env, "")

    async def __manifest(x_symverify_token: str | None = Header(default=None, alias="X-Symverify-Token")):
        if not expected_token:
            raise HTTPException(503, "manifest endpoint disabled (SYMVERIFY_TOKEN unset)")
        if not x_symverify_token or not hmac.compare_digest(x_symverify_token, expected_token):
            raise HTTPException(401, "unauthorized")
        return Response(
            content=cached_body,
            media_type="application/json",
            headers={"Cache-Control": "no-store"},
        )

    app.add_api_route(route, __manifest, methods=["GET"])
    return app
'''


def _caddy_snippet(app_name: str) -> str:
    return f"""\
# Generated by `sym scaffold` for {app_name}.
# Merge into server/Caddyfile under the appropriate hostname block.

{app_name}.symmetism.com {{
    encode gzip zstd
    log {{
        output file /var/log/caddy/{app_name}.access.log {{
            roll_size 20mb
            roll_keep 5
        }}
    }}
    reverse_proxy {app_name}:8000 {{
        transport http {{
            read_timeout 60s
            dial_timeout 5s
        }}
    }}
}}
"""


# ---------------------------------------------------------------------------
# Result type + main entry
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class ScaffoldResult:
    """Files written + summary."""

    app_name: str
    repo_name: str
    app_dir: Path
    files_written: list[Path]
    caddy_snippet_path: Path


def scaffold_app(
    target: str,
    *,
    force: bool = False,
) -> ScaffoldResult:
    """Generate a new app skeleton at <repo>/apps/<app-name>/."""
    if "/" not in target:
        raise ScaffoldError("expected <repo>/<app-name> (e.g. platform/foo)")
    repo_name, app_name = target.split("/", 1)
    _validate_app_name(app_name)
    pkg_name = _pkg_name(app_name)

    repos = config.load_repos()
    if repo_name not in repos:
        raise ScaffoldError(
            f"repo '{repo_name}' not configured; have: {sorted(repos)}"
        )
    repo_path = repos[repo_name].path
    app_dir = repo_path / "apps" / app_name

    if app_dir.exists() and not force:
        raise ScaffoldError(f"refusing to clobber existing dir {app_dir} (pass force=True)")

    app_dir.mkdir(parents=True, exist_ok=True)
    src_dir = app_dir / "src" / pkg_name
    src_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []

    def _write(path: Path, content: str) -> None:
        path.write_text(content, encoding="utf-8")
        written.append(path)

    _write(app_dir / "pyproject.toml", _pyproject(app_name, pkg_name))
    _write(app_dir / "Dockerfile", _dockerfile(app_name, pkg_name, repo_name))
    _write(app_dir / "README.md", _readme(app_name))
    _write(src_dir / "__init__.py", _init_py(app_name))
    _write(src_dir / "main.py", _main_py(app_name, pkg_name))
    _write(src_dir / "manifest_endpoint.py", _manifest_endpoint_py(pkg_name))

    caddy_path = app_dir / "caddy-snippet.txt"
    _write(caddy_path, _caddy_snippet(app_name))

    return ScaffoldResult(
        app_name=app_name,
        repo_name=repo_name,
        app_dir=app_dir,
        files_written=written,
        caddy_snippet_path=caddy_path,
    )
